/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    rotate: {
      "-180": "-180deg",
      "-90": "-90deg",
      "-45": "-45deg",
      0: "0",
      45: "45deg",
      90: "90deg",
      135: "135deg",
      180: "180deg",
      270: "270deg",
    },
    extend: {
      fontFamily: {
        body: ["var(--font-quicksand)", "sans-serif"],
        heading: ["var(--font-comfortaa)", "sans-serif"],
        "sub-heading": ["var(--font-merriweather)", "serif"],
        tech: ["var(--font-ibm-plex-mono)", "monospace"],
      },
      colors: {
        primary: {
          DEFAULT: "#005BB0",
          light: "#3E8DDA",
        },
        secondary: {
          DEFAULT: "#B05500",
          light: "#E07A20",
        },
        accent: {
          green: "#00A896",
          coral: "#FF5A5A",
        },
        neutral: {
          offwhite: "#F7F7F7",
          "light-gray": "#E5E5E5",
          "medium-gray": "#A0A0A0",
          "dark-gray": "#4A4A4A",
        },
        text: {
          primary: "#2B2B2B",
          secondary: "#5F5F5F",
        },
        background: {
          primary: "#FFFFFF",
          secondary: "#FAFAFA",
        },
        error: "#C90000",
        success: "#00C968",
      },
      // colors: {
      //   primary: "#b3b4bd",
      //   // primary: "#0068C9",
      //   navbar: "#8b8b8f",
      //   // secondary: "#00C9C6",
      //   // secondary: "#C96100",
      //   paragraph: "#141619",
      //   "paragraph-light": "#2d3135",
      //   scd: "#2c2e3a",
      //   "scd-light": "#4f5160",
      //   heading: "#4f4f59",
      //   secondary: "#050a44",
      //   tertiary: "#0a21c0",
      //   error: "#C90068",
      //   success: "#68C900",
      //   "resume-hover": "#0a21c0",
      //   startup: "#020c1b",
      // },
      // colors: {
      //   primary: "#033b75",
      //   // primary: "#0068C9",
      //   navbar: "#0003C9",
      //   // secondary: "#00C9C6",
      //   // secondary: "#C96100",
      //   secondary: "#87cdfa",
      //   tertiary: "#112340",
      //   error: "#C90068",
      //   success: "#68C900",
      //   "resume-hover": "#153040",
      //   startup: "#020c1b",
      // },
      // colors: {
      //   primary: "#0b192f",
      //   secondary: "#64ffda",
      //   error: "#ff6489",
      //   tertiary: "#112340",
      //   "resume-hover": "#153040",
      //   navbar: "#112340",
      //   startup: "#020c1b",
      // },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
